version: '3.8'

services:
  # 1. Database Service
  mongo:
    image: mongo
    container_name: elibrary-mongo
    ports:
      - "27017:27017"
    volumes:
      # THIS LINE SAVES DATA TO YOUR HARD DRIVE
      - mongo-data:/data/db 
    networks:
      - elibrary-network

  # 2. Backend Service
  server:
    build: ./server
    container_name: elibrary-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/elibrary
    depends_on:
      - mongo
    networks:
      - elibrary-network

  # 3. Frontend Service
  client:
    build: ./client
    container_name: elibrary-client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - elibrary-network

  # 4. Custom Ubuntu Nagios Service
  nagios:
    build: ./nagios_ubuntu
    container_name: elibrary-nagios-ubuntu
    ports:
      - "9090:80"
    networks:
      - elibrary-network

volumes:
  mongo-data:

networks:
  elibrary-network:
    driver: bridge